services:

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  nest1:
    build:
      context: .
      dockerfile: apps/order_service/Dockerfile
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    container_name: order_service
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - postgres
      - rabbit

  nest2:
    build:
      context: .
      dockerfile: apps/payment-worker/Dockerfile
    container_name: payment-worker
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - rabbit

volumes:
  postgres_data:
